apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-sa-op-${NAMESPACE}
secrets:
- name: ns-sa-op-${NAMESPACE}-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ns-sa-${NAMESPACE}
secrets:
- name: ns-sa-${NAMESPACE}-token
---
apiVersion: v1
kind: Secret
metadata:
  name: ns-sa-op-${NAMESPACE}-token
  annotations:
    kubernetes.io/service-account.name: ns-sa-op-${NAMESPACE}
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: ns-sa-${NAMESPACE}-token
  annotations:
    kubernetes.io/service-account.name: ns-sa-${NAMESPACE}
type: kubernetes.io/service-account-token
